const state={lang:'ar',mood:'calm',finish:'walnut',quote:[]};
const moods={
 calm:{image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=88',ar:['هدوءٌ له ملمس.','خشب دافئ، كتان طبيعي، ومسافات تتنفس.'],en:['Quiet, with texture.','Warm wood, natural linen, and room to breathe.'],price:8450},
 bold:{image:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1800&q=88',ar:['لونٌ يغيّر الإيقاع.','تباين جريء، خطوط نظيفة، وقطعة واحدة تقود المشهد.'],en:['Color shifts the rhythm.','Bold contrast, clean lines, and one object leading the scene.'],price:9720},
 earth:{image:'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1800&q=88',ar:['الأرض داخل البيت.','طين محروق، ألياف خام، وخشب يحفظ أثر اليد.'],en:['Bring earth indoors.','Burnt clay, raw fibers, and wood that keeps the maker’s touch.'],price:10850}
};
const finishAdd={walnut:0,oak:650,stone:1250};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function money(n){return state.lang==='ar'?`${n.toLocaleString('en-US')} ل.س`:`SYP ${n.toLocaleString('en-US')}`}
function updateStudio(){const d=moods[state.mood],stage=$('#roomStage');stage.classList.add('changing');setTimeout(()=>{ $('#roomImage').src=d.image;$('#roomTitle').textContent=d[state.lang][0];$('#roomDesc').textContent=d[state.lang][1];$('#roomPrice').textContent=money(d.price+finishAdd[state.finish]);stage.classList.remove('changing')},260);const p=state.mood==='calm'?72:state.mood==='bold'?86:94;$('#meterFill').style.width=p+'%';$('#meterText').textContent=p+'%'}
$('#moods').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.mood=b.dataset.mood;$$('#moods button').forEach(x=>x.classList.toggle('active',x===b));updateStudio()});
$('#finishes').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.finish=b.dataset.finish;$$('#finishes button').forEach(x=>x.classList.toggle('active',x===b));updateStudio();chairMaterial.color.set(b.dataset.finish==='walnut'?0x6d4c36:b.dataset.finish==='oak'?0xc6a36d:0xd9d4c8)});
function showToast(ar,en){const t=$('#toast');t.textContent=state.lang==='ar'?ar:en;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function addQuote(nameAr,nameEn,price){state.quote.push({nameAr,nameEn,price,id:Date.now()+Math.random()});renderQuote();showToast('انضافت لاختياراتك','Added to your quote')}
$('#addRoom').onclick=()=>{const d=moods[state.mood];addQuote(`غرفة ${d.ar[0]}`,`${d.en[0]} room`,d.price+finishAdd[state.finish])};
$$('.add-product').forEach(b=>b.onclick=()=>{const p=b.closest('.product');addQuote(p.dataset.nameAr,p.dataset.nameEn,+p.dataset.price)});
function renderQuote(){const wrap=$('#quoteItems');$('#quoteCount').textContent=state.quote.length;if(!state.quote.length){wrap.innerHTML=`<p class="empty">${state.lang==='ar'?'اختياراتك رح تظهر هون.':'Your selections will appear here.'}</p>`}else{wrap.innerHTML=state.quote.map(x=>`<div class="quote-line"><span>${state.lang==='ar'?x.nameAr:x.nameEn}</span><b>${money(x.price)}</b><button data-remove="${x.id}" aria-label="remove">×</button></div>`).join('')}$('#quoteTotal').textContent=money(state.quote.reduce((a,x)=>a+x.price,0));wrap.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.quote=state.quote.filter(x=>x.id!=b.dataset.remove);renderQuote()})}
$('#filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));$$('.product').forEach(p=>p.classList.toggle('hidden',b.dataset.filter!=='all'&&p.dataset.cat!==b.dataset.filter))};
$$('[data-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go).scrollIntoView({behavior:'smooth'}));
$('#langBtn').onclick=()=>{state.lang=state.lang==='ar'?'en':'ar';document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';$('#langBtn').textContent=state.lang==='ar'?'EN':'ع';$$('[data-ar]').forEach(el=>el.textContent=el.dataset[state.lang]);updateStudio();renderQuote()};
const vid=$('#craftVideo'),vbtn=$('#videoToggle');vbtn.onclick=()=>{if(vid.paused){vid.play();vbtn.classList.remove('playing');vbtn.querySelector('span:last-child').textContent=state.lang==='ar'?'إيقاف':'Pause'}else{vid.pause();vbtn.classList.add('playing');vbtn.querySelector('span:last-child').textContent=state.lang==='ar'?'تشغيل':'Play'}};
$('#quoteForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),items=state.quote.map(x=>state.lang==='ar'?x.nameAr:x.nameEn).join('، '),total=state.quote.reduce((a,x)=>a+x.price,0);const msg=state.lang==='ar'?`مرحباً مِحور، أنا ${fd.get('name')} من ${fd.get('city')}. أريد عرضاً لـ: ${items||'تصميم غرفة'}. التقدير: ${money(total)}.`:`Hello Mihwar, I’m ${fd.get('name')} from ${fd.get('city')}. I would like a quote for: ${items||'a room design'}. Estimate: ${money(total)}.`;window.open(`https://wa.me/963999000000?text=${encodeURIComponent(msg)}`,'_blank')};
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));

// Transparent, hand-built Three.js chair: integrated spatial signature.
const canvas=$('#chair3d'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;camera.position.set(4,3.1,5.5);camera.lookAt(0,1,0);const chair=new THREE.Group();scene.add(chair);const chairMaterial=new THREE.MeshPhysicalMaterial({color:0x6d4c36,roughness:.36,metalness:.02,clearcoat:.25});const textile=new THREE.MeshStandardMaterial({color:0xd8c9ad,roughness:.9});function box(w,h,d,x,y,z,mat=chairMaterial,rx=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.rotation.x=rx;chair.add(m);return m}box(2.2,.28,2,0,1.55,0,textile);box(2.3,.18,.18,0,3.05,-.85);for(let y=2.05;y<3;y+=.28)box(2.05,.12,.12,0,y,-.83,chairMaterial,-.05);[[-.9,0], [.9,0]].forEach(([x])=>{box(.17,1.8,.17,x,.7,.67);box(.17,2.8,.17,x,1.4,-.73)});box(2.05,.13,.13,0,.25,.63);chair.rotation.y=-.5;scene.add(new THREE.HemisphereLight(0xffffff,0x372718,3));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(4,6,4);scene.add(light);let drag=false,last=0;canvas.addEventListener('pointerdown',e=>{drag=true;last=e.clientX;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){chair.rotation.y+=(e.clientX-last)*.012;last=e.clientX}});canvas.addEventListener('pointerup',()=>drag=false);function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();(function loop(t){if(!drag)chair.rotation.y+=.002;chair.position.y=Math.sin(t*.001)*.04;renderer.render(scene,camera);requestAnimationFrame(loop)})(0);
